#!/usr/bin/env bash
# Install and run duty1g's x64dbg MCP plugin under Proton. Everything mutable stays in the
# gitignored .re-tools tree; only this pinned, project-scoped recipe is committed.
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
TOOL_DIR=${X64DBG_MCP_DIR:-"$ROOT/.re-tools/x64dbg-mcp"}
X64DBG_URL=https://github.com/x64dbg/x64dbg/releases/download/2026.05.27/snapshot_2026-05-27_12-11.zip
X64DBG_SHA=d41966dfc5b435a372798245300ca0ab7bb8e48bdbf48512c6fb20fcca427697
PLUGIN_URL=https://github.com/duty1g/x64dbg-mcp-server/releases/download/1.0/x64dbg-MCP-Server-v1.0.zip
PLUGIN_SHA=4ad4ccbc047c71e38e4c06b7e690a9f74d3d7772019e567ab2d789aeb7d5716b
USER_AGENT='OpenAI File Downloader, XaiImageApiFetch/1.0'
TOKEN_FILE="$TOOL_DIR/auth-token"
ENV_FILE="$TOOL_DIR/env.sh"
EXE="$TOOL_DIR/release/x64/x64dbg.exe"
CONFIG="$TOOL_DIR/release/x64/mcp_config.json"

die() { printf 'x64dbg-mcp: %s\n' "$*" >&2; exit 1; }
note() { printf 'x64dbg-mcp: %s\n' "$*"; }

hash_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

download() {
  local url=$1 expected=$2 output=$3 actual
  curl -fL --retry 3 --user-agent "$USER_AGENT" -o "$output" "$url"
  actual=$(hash_file "$output")
  [[ "$actual" == "$expected" ]] || die "checksum mismatch for $url (got $actual)"
}

write_runtime_config() {
  local token
  if [[ ! -s "$TOKEN_FILE" ]]; then
    umask 077
    openssl rand -hex 16 > "$TOKEN_FILE"
  fi
  token=$(tr -d '\r\n' < "$TOKEN_FILE")
  [[ "$token" =~ ^[0-9a-fA-F]{32}$ ]] || die "invalid token in $TOKEN_FILE"
  umask 077
  printf '{"IpAddress":"127.0.0.1","Port":9094,"AutoStart":true,"AuthToken":"%s"}\n' "$token" > "$CONFIG"
  printf '# Generated by scripts/re/x64dbg-mcp.sh. Source before starting Codex.\nexport X64DBG_MCP_TOKEN=%q\n' "$token" > "$ENV_FILE"
  chmod 600 "$TOKEN_FILE" "$ENV_FILE" "$CONFIG"
}

cmd_install() {
  command -v curl >/dev/null || die 'curl is required'
  command -v unzip >/dev/null || die 'unzip is required'
  command -v openssl >/dev/null || die 'openssl is required'
  command -v sha256sum >/dev/null || command -v shasum >/dev/null || die 'sha256sum or shasum is required'

  local work stage backup saved_token
  work=$(mktemp -d "${TMPDIR:-/tmp}/unseamless-x64dbg-mcp.XXXXXX")
  trap 'rm -rf "$work"' RETURN
  stage="$work/install"
  saved_token="$work/auth-token"
  [[ -s "$TOKEN_FILE" ]] && cp "$TOKEN_FILE" "$saved_token"
  note 'downloading pinned x64dbg 2026.05.27'
  download "$X64DBG_URL" "$X64DBG_SHA" "$work/x64dbg.zip"
  note 'downloading pinned x64dbg MCP server 1.0'
  download "$PLUGIN_URL" "$PLUGIN_SHA" "$work/plugin.zip"

  mkdir -p "$stage"
  unzip -q "$work/x64dbg.zip" -d "$stage"
  unzip -q "$work/plugin.zip" -d "$stage/release"
  [[ -f "$stage/release/x64/x64dbg.exe" ]] || die 'x64dbg archive is incomplete'
  [[ -f "$stage/release/x64/plugins/x64dbg-MCP-Server.dp64" ]] \
    || die 'archive did not install the x64 MCP plugin'
  mkdir -p "$(dirname "$TOOL_DIR")"
  if [[ -e "$TOOL_DIR" ]]; then
    backup="${TOOL_DIR}.replaced.$(date -u +%Y%m%dT%H%M%SZ)"
    mv "$TOOL_DIR" "$backup"
    note "preserved previous install at $backup"
  fi
  if ! mv "$stage" "$TOOL_DIR"; then
    [[ -n "${backup:-}" && -d "$backup" ]] && mv "$backup" "$TOOL_DIR"
    die 'failed to activate the fresh install'
  fi
  [[ -s "$saved_token" ]] && cp "$saved_token" "$TOKEN_FILE"
  write_runtime_config
  note "installed in $TOOL_DIR"
  note "next: source '$ENV_FILE' && scripts/re/x64dbg-mcp.sh launch"
}

find_proton() {
  if [[ -n "${X64DBG_PROTON:-}" ]]; then
    printf '%s\n' "$X64DBG_PROTON"
    return
  fi
  local steam_root=${STEAM_ROOT:-"$HOME/.local/share/Steam"} candidate
  for candidate in \
    "$steam_root/steamapps/common/Proton - Experimental/proton" \
    "$steam_root/steamapps/common/Proton Hotfix/proton"; do
    [[ -x "$candidate" ]] && { printf '%s\n' "$candidate"; return; }
  done
  while read -r candidate; do
    [[ -x "$candidate" ]] && { printf '%s\n' "$candidate"; return; }
  done < <(find "$steam_root/steamapps/common" -maxdepth 2 -type f -name proton \
    \( -path '*/Proton*/*' -o -path '*/GE-Proton*/*' \) -print 2>/dev/null | sort -r)
  die 'Proton not found; set X64DBG_PROTON to a Proton launcher path'
}

cmd_launch() {
  [[ $(uname -s) == Linux ]] || die 'launch is Linux-only (install and static checks work on macOS)'
  [[ -f "$EXE" && -f "$ENV_FILE" ]] || die 'not installed; run install first'
  local proton steam_root compat_data
  proton=$(find_proton)
  steam_root=${STEAM_ROOT:-"$HOME/.local/share/Steam"}
  compat_data=${X64DBG_COMPAT_DATA:-"$steam_root/steamapps/compatdata/1245620"}
  [[ -d "$compat_data" ]] || die "ELDEN RING Proton prefix not found: $compat_data"
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  export STEAM_COMPAT_CLIENT_INSTALL_PATH="$steam_root"
  export STEAM_COMPAT_DATA_PATH="$compat_data"
  note 'starting x64dbg; the MCP plugin binds only to 127.0.0.1:9094'
  if [[ $# -gt 0 ]]; then
    exec "$proton" run "$EXE" -p "$1"
  fi
  exec "$proton" run "$EXE"
}

cmd_probe() {
  [[ -s "$TOKEN_FILE" ]] || die 'not installed; run install first'
  local token response
  token=$(tr -d '\r\n' < "$TOKEN_FILE")
  response=$(mktemp "${TMPDIR:-/tmp}/unseamless-x64dbg-probe.XXXXXX")
  trap 'rm -f "$response"' RETURN
  curl -fsS --user-agent "$USER_AGENT" \
    -H "Authorization: Bearer $token" \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json, text/event-stream' \
    --data '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"unseamless-probe","version":"1"}}}' \
    -o "$response" http://127.0.0.1:9094/
  grep -q '"result"' "$response" || die 'server replied, but MCP initialization failed'
  note 'authenticated MCP initialization succeeded'
}

cmd_doctor() {
  local failed=0
  for path in "$EXE" "$TOOL_DIR/release/x64/plugins/x64dbg-MCP-Server.dp64" "$CONFIG" "$TOKEN_FILE" "$ENV_FILE"; do
    if [[ -f "$path" ]]; then note "ok: $path"; else note "missing: $path"; failed=1; fi
  done
  if [[ -f "$CONFIG" ]] && grep -q '"IpAddress":"127.0.0.1"' "$CONFIG"; then
    note 'ok: server is loopback-only'
  else
    note 'invalid: MCP server is not pinned to loopback'; failed=1
  fi
  if [[ $(uname -s) != Linux ]]; then
    note 'runtime launch remains intentionally unvalidated until CachyOS'
  elif ! command -v gamescope >/dev/null 2>&1; then
    note 'warning: gamescope is missing (not required by x64dbg itself)'
  fi
  return "$failed"
}

usage() {
  cat <<'EOF'
Usage: scripts/re/x64dbg-mcp.sh COMMAND

  install        download verified, pinned x64dbg + MCP plugin archives
  doctor         validate the local install and loopback-only configuration
  launch [WINPID] run x64dbg in ELDEN RING's Proton prefix, optionally attaching to a Windows PID
  probe          authenticate and initialize an MCP session against the running plugin
  env            print the env-file path to source before starting Codex
EOF
}

case ${1:-help} in
  install) cmd_install ;;
  doctor) cmd_doctor ;;
  launch) shift; cmd_launch "$@" ;;
  probe) cmd_probe ;;
  env) printf '%s\n' "$ENV_FILE" ;;
  help|-h|--help) usage ;;
  *) usage >&2; exit 2 ;;
esac
